import sendgrid
from sendgrid.helpers.mail import Mail, Attachment, FileContent, FileName
from sendgrid.helpers.mail import FileType, Disposition
from dotenv import load_dotenv
import os
import base64

load_dotenv()

def email_agent(report_output: dict, recipient_email: str) -> dict:

    print(f"📧 Email Agent started...")
    print(f"   Sending to: {recipient_email}")

    original_query = report_output["original_query"]
    filename       = report_output["filename"]
    total          = report_output["total"]
    query_plan     = report_output["query_plan"]
    report_title   = query_plan.get("report_title", "GCC BI Report")
    countries      = query_plan.get("countries", [])
    sector         = query_plan.get("sector", "")
    query_type     = query_plan.get("query_type", "").replace("_", " ").title() 
    time_period    = query_plan.get("time_period", "Recent")                    

    # ── READ REPORT FILE ─────────────────────────────────

    # Check file exists before doing anything
    if not os.path.exists(filename):
        print(f"   ❌ Report file not found: {filename}")
        return {"success": False, "error": "Report file not found"}

    # Read file and convert to base64
    with open(filename, "rb") as f:
        file_data    = f.read()
        encoded_file = base64.b64encode(file_data).decode()

    # Get just filename without full path
    attachment_name = os.path.basename(filename)

    # ── BUILD EMAIL ──────────────────────────────────────

    subject = f"GCC BI Report Ready — {original_query}"


    body = f"""
<html>
<body style="font-family: Arial, sans-serif; color: #333;">

    <h2 style="color: #1a5276;">
        GCC AI & Startup Intelligence Platform
    </h2>

    <p>Your business intelligence report is ready.</p>

    <table style="border-collapse: collapse; width: 100%;">
        <tr>
            <td style="padding: 8px; font-weight: bold;">Query:</td>
            <td style="padding: 8px;">{original_query}</td>
        </tr>
        <tr style="background: #f2f2f2;">
            <td style="padding: 8px; font-weight: bold;">Report Title:</td>
            <td style="padding: 8px;">{report_title}</td>
        </tr>
        <tr>
            <td style="padding: 8px; font-weight: bold;">Countries Covered:</td>
            <td style="padding: 8px;">{', '.join(countries)}</td>
        </tr>
        <tr style="background: #f2f2f2;">
            <td style="padding: 8px; font-weight: bold;">Sector:</td>
            <td style="padding: 8px;">{sector.title()}</td>
        </tr>
        <tr>
            <td style="padding: 8px; font-weight: bold;">Total Entities Found:</td>
            <td style="padding: 8px;">{total}</td>
        </tr>
        <tr style="background: #f2f2f2;">
            <td style="padding: 8px; font-weight: bold;">Query Type:</td>
            <td style="padding: 8px;">{query_type}</td>
        </tr>
        <tr>
            <td style="padding: 8px; font-weight: bold;">Time Period:</td>
            <td style="padding: 8px;">{time_period}</td>
        </tr>
    </table>

    <br>
    <p>Please find the full report attached as a Word document.</p>

    <hr>
    <p style="color: #888; font-size: 12px;">
        Generated by GCC AI & Startup Intelligence Platform<br>
        Powered by Multi-Agent AI Pipeline
    </p>

</body>
</html>
"""

    # ── ATTACH REPORT FILE ───────────────────────────────

    attachment = Attachment(
        FileContent(encoded_file),
        FileName(attachment_name),
        FileType("application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
        Disposition("attachment")
    )

    # ── SEND EMAIL ───────────────────────────────────────

    message = Mail(
        from_email   = os.getenv("SENDER_EMAIL"),
        to_emails    = recipient_email,
        subject      = subject,
        html_content = body
    )
    message.attachment = attachment

    try:
        sg       = sendgrid.SendGridAPIClient(api_key=os.getenv("SENDGRID_API_KEY"))
        response = sg.send(message)

        if response.status_code in [200, 202]:
            print(f"   ✅ Email sent successfully!")
            print(f"   📬 Status code: {response.status_code}")
            return {
                "success":    True,
                "recipient":  recipient_email,
                "subject":    subject,
                "attachment": attachment_name,
                "status":     response.status_code
            }
        else:
            print(f"   ❌ Email failed. Status: {response.status_code}")
            return {
                "success": False,
                "error":   f"Status code: {response.status_code}"
            }

    except Exception as e:
        print(f"   ❌ Email error: {e}")
        return {
            "success": False,
            "error":   str(e)
        }