from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime
import os

def report_agent(analysis_output: dict) -> dict:

    print(f"📝 Report Agent started...")

    original_query = analysis_output["original_query"]
    query_plan     = analysis_output["query_plan"]
    items          = analysis_output["items"]
    total          = analysis_output["total"]
    report_title   = query_plan.get("report_title", "GCC Business Intelligence Report")
    query_type     = query_plan.get("query_type", "startup_discovery")
    countries      = query_plan.get("countries", [])
    sector         = query_plan.get("sector", "")
    extract_fields = query_plan.get("extract_fields", [])

   
    sector_display = "AI" if sector.lower() == "ai" else sector.title()

    # Create Word document
    doc = Document()

    # ── TITLE PAGE ───────────────────────────────────────

    doc.add_paragraph("")
    doc.add_paragraph("")

    title = doc.add_heading(report_title, level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph("")

    subtitle = doc.add_paragraph(f'Query: "{original_query}"')
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.runs[0].font.size = Pt(13)
    subtitle.runs[0].font.italic = True

    doc.add_paragraph("")

    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta.add_run(f"Generated by GCC AI & Startup Intelligence Platform\n")
    meta.add_run(f"Date: {datetime.now().strftime('%B %d, %Y')}\n")
    meta.add_run(f"Countries Covered: {', '.join(countries)}\n")
    meta.add_run(f"Sector: {sector_display}")

    doc.add_page_break()

    # ── EXECUTIVE SUMMARY ────────────────────────────────

    doc.add_heading("Executive Summary", level=1)

   
    funded = [
        item for item in items
        if item.get("funding", "Unknown") not in ["Unknown", "N/A", ""]
        or item.get("amount",  "Unknown") not in ["Unknown", "N/A", ""]
        or item.get("value",   "Unknown") not in ["Unknown", "N/A", ""]
    ]

    summary = doc.add_paragraph()
    summary.add_run(f"""This report presents the findings of an automated AI-powered \
research pipeline for the query: "{original_query}". \
A total of {total} entities were identified across \
{', '.join(countries)} through intelligent web research and \
AI-based data extraction.\n\n""")

    summary.add_run(f"Report Type: ").bold = True
    summary.add_run(f"{query_type.replace('_', ' ').title()}\n")

    summary.add_run(f"Total Entities Found: ").bold = True
    summary.add_run(f"{total}\n")

    summary.add_run(f"Entities with Data Values: ").bold = True
    summary.add_run(f"{len(funded)}\n")

    summary.add_run(f"Countries Covered: ").bold = True
    summary.add_run(f"{', '.join(countries)}\n")

    summary.add_run(f"Sector Focus: ").bold = True
    summary.add_run(f"{sector_display}\n")

    summary.add_run(f"Report Generated: ").bold = True
    summary.add_run(f"{datetime.now().strftime('%B %d, %Y at %H:%M')}")

    doc.add_page_break()

    # ── OVERVIEW TABLE ───────────────────────────────────

    doc.add_heading("Data Overview Table", level=1)
    doc.add_paragraph(
        f"The table below summarizes all {total} entities identified:"
    )
    doc.add_paragraph("")

    # Remove source_url from table — too long
    table_fields = [f for f in extract_fields if f != "source_url"]

    table = doc.add_table(rows=1, cols=len(table_fields) + 1)
    table.style = "Table Grid"

    # Header row
    header_cells = table.rows[0].cells
    header_cells[0].text = "#"
    for col_idx, field in enumerate(table_fields):
        header_cells[col_idx + 1].text = field.replace("_", " ").title()
        for para in header_cells[col_idx + 1].paragraphs:
            for run in para.runs:
                run.bold = True

    # Make # header bold too
    for para in header_cells[0].paragraphs:
        for run in para.runs:
            run.bold = True

    # Data rows
    for idx, item in enumerate(items):
        row_cells = table.add_row().cells
        row_cells[0].text = str(idx + 1)
        for col_idx, field in enumerate(table_fields):
            value = str(item.get(field, "Unknown"))
            row_cells[col_idx + 1].text = value[:60] + "..." if len(value) > 60 else value

    doc.add_page_break()

    # ── DETAILED PROFILES ────────────────────────────────

    doc.add_heading("Detailed Profiles", level=1)

    for idx, item in enumerate(items):

        # Get best name field — works for all query types
        name = (
            item.get("name")             or  # startup_discovery
            item.get("company")          or  # funding_intelligence
            item.get("entity")           or  # comparison
            item.get("insight", "")[:50] or  # sector_report
            f"Item {idx + 1}"
        )

        doc.add_heading(f"{idx + 1}. {name}", level=2)

        details = doc.add_paragraph()

        for field in extract_fields:
            value = item.get(field, "Unknown")
            if value and value not in ["Unknown", "N/A", ""]:
                label = field.replace("_", " ").title()
                details.add_run(f"• {label}: ").bold = True
                if field == "source_url" and len(str(value)) > 80:
                    details.add_run(f"{str(value)[:80]}...\n")
                else:
                    details.add_run(f"{value}\n")

        doc.add_paragraph("─" * 55)

    # ── SAVE FILE ────────────────────────────────────────

    date_str   = datetime.now().strftime("%Y%m%d_%H%M")
    safe_name  = original_query.replace(" ", "_")[:30]
    outputs_dir = "/tmp/outputs" if os.path.exists("/tmp") else "outputs"
    os.makedirs(outputs_dir, exist_ok=True)
    filename   = f"{outputs_dir}/GCC_BI_Report_{safe_name}_{date_str}.docx"

    doc.save(filename)
    print(f"✅ Report saved: {filename}")

    return {
        "original_query": original_query,
        "query_plan":     query_plan,
        "filename":       filename,
        "total":          total
    }